apiVersion: v1
kind: Service
metadata:
  name: mailout-webhook
  namespace: mailout-system
spec:
  selector:
    app.kubernetes.io/name: mailout
    app.kubernetes.io/component: operator
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
